name: Check Pull Request

on:
  pull_request:
    branches: [main] # Ganti dengan branch yang ingin Anda lindungi (misalnya, stable)

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npm test # Ganti dengan perintah pengujian Anda (misalnya, yarn test, pytest)
      - name: Check checklist
        if: github.event.pull_request.body !contains '[ ]'
        run: echo "Checklist belum lengkap!"
        exit 1
